package com.example.owl.models;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

/**
 * Created by Zach on 6/5/17.
 */

@DynamoDBTable(tableName = "Photo")
public class Photo {
    private String PhotoId;
    private String UploadDate;
    private String UserId;
    private String Photo;


    public Photo() {
    }


    @DynamoDBHashKey(attributeName = "PhotoId")
    @DynamoDBAutoGeneratedKey
    public String getPhotoId() {
        return PhotoId;
    }

    public void setPhotoId(String photoId) {
        PhotoId = photoId;
    }

    @DynamoDBAttribute(attributeName = "UserId")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "UserId-UploadDate-index", attributeName = "UserId")
    public String getUserId() {
        return UserId;
    }

    public void setUserId(String userId) {
        UserId = userId;
    }

    @DynamoDBRangeKey(attributeName = "UploadDate")
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "UserId-UploadDate-index", attributeName = "UploadDate")
    public String getUploadDate() {
        return UploadDate;
    }

    public void setUploadDate(String uploadDate) {
        UploadDate = uploadDate;
    }

    @DynamoDBAttribute(attributeName = "Photo")
    public String getPhoto() {
        return Photo;
    }

    public void setPhoto(String photo) {
        Photo = photo;
    }
}
