package com.example.owl.models;

import android.graphics.Color;
import android.graphics.drawable.Drawable;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

/**
 * Created by Zach on 5/25/17.
 */

@DynamoDBTable(tableName = "User")
public class User {

    private String mUserId;
    private String mName;
    private String mBio;
    private String mJoinDate;
    private String mPhoto;
    //private Color mColor;



    public User() {

    }

    public User(String userId, String name, String bio, String joinDate, String photo) {
        mUserId = userId;
        mName = name;
        mBio = bio;
        mJoinDate = joinDate;
        mPhoto = photo;
    }



    @DynamoDBHashKey(attributeName = "UserId")
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return mUserId;
    }

    public void setUserId(String userId) {
        mUserId = userId;
    }

    @DynamoDBAttribute(attributeName = "Name")
    public String getName() {
        return mName;
    }

    public void setName(String name) {
        mName = name;
    }

    @DynamoDBAttribute(attributeName = "Bio")
    public String getBio() {
        return mBio;
    }

    public void setBio(String bio) {
        mBio = bio;
    }

    @DynamoDBAttribute(attributeName = "JoinDate")
    public String getJoinDate() {
        return mJoinDate;
    }

    public void setJoinDate(String joinDate) {
        mJoinDate = joinDate;
    }

    @DynamoDBAttribute(attributeName = "Photo")
    public String getPhoto() {
        return mPhoto;
    }

    public void setPhoto(String photo) {
        mPhoto = photo;
    }

    /*
    public Color getColor() {
        return mColor;
    }

    public void setColor(Color color) {
        mColor = color;
    }
    */

}
